config/routes.rb
Rails.application.routes.draw do
  resources :polls
  get 'profile', to: 'profile#index'
  get 'scheduler', to: 'scheduler#new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poll.rb
class Poll < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController

end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: %i[ show edit update destroy ]

  # GET /polls or /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1 or /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls or /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to poll_url(@poll), notice: "Poll was successfully created." }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1 or /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to poll_url(@poll), notice: "Poll was successfully updated." }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1 or /polls/1.json
  def destroy
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url, notice: "Poll was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def poll_params
      params.require(:poll).permit(:title, :description)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    def index
        
    end
end

app/controllers/scheduler_controller.rb
class SchedulerController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Canary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class='container'>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/index.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/polls/_form.html.erb
<%= form_with(model: poll) do |form| %>
  <% if poll.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
        <% poll.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/polls/_poll.html.erb
<div id="<%= dom_id poll %>">
  <p>
    <strong>Title:</strong>
    <%= poll.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= poll.description %>
  </p>

</div>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render "form", poll: @poll %>

<br>

<div>
  <%= link_to "Show this poll", @poll %> |
  <%= link_to "Back to polls", polls_path %>
</div>

app/views/polls/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Polls</h1>

<div id="polls">
  <% @polls.each do |poll| %>
    <%= render poll %>
    <p>
      <%= link_to "Show this poll", poll %>
    </p>
  <% end %>
</div>

<%= link_to "New poll", new_poll_path %>

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render "form", poll: @poll %>

<br>

<div>
  <%= link_to "Back to polls", polls_path %>
</div>

app/views/polls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @poll %>

<div>
  <%= link_to "Edit this poll", edit_poll_path(@poll) %> |
  <%= link_to "Back to polls", polls_path %>

  <%= button_to "Destroy this poll", @poll, method: :delete %>
</div>

app/views/scheduler/new.html.erb
<h1>Create a poll</h1>


<form>
    <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        <label for="exampleInputPassword1" class="form-label">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1">
    </div>
    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <%= link_to 'Canary', root_path, class:'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to "Schedule a Meeting", scheduler_path, class: 'nav-link' %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>